#!/usr/bin/env python3
"""
CLI for Rocky Branches Road Network population analysis.

This module provides a command-line interface to run the justPop.exe program
for computing population within a radius of a given point.

Usage:
    rb-road-network run          # Interactive mode
    rb-road-network run --help   # Show options
    rb-road-network run -f output.txt -t 4.5 --lat 33.732 --lon -84.4166
    rb-road-network batch --csv batch_inputs.csv
"""

import csv
import os
import sys
import subprocess
from pathlib import Path

import click

DEFAULT_OUTPUT = "output/justPopResult.txt"
DEFAULT_TONS_PER_PERSON = 4.50
DEFAULT_LAT = 33.732
DEFAULT_LON = -84.4166
DEFAULT_RADIUS = 75000
DEFAULT_STRIDE = 0.009
DEFAULT_ZOOM = 0.5


def get_rb_src() -> Path:
    """Get RB_SRC directory from environment or default to current directory."""
    rb_src = os.environ.get("RB_SRC")
    if rb_src:
        return Path(rb_src)
    return Path.cwd()


def get_justpop_exe(rb_src: Path) -> Path:
    """Get path to justPop.exe."""
    exe_path = rb_src / "justPop.exe"
    if not exe_path.exists():
        raise FileNotFoundError(f"justPop.exe not found at {exe_path}")
    return exe_path


def build_command(
    exe_path: Path,
    output: Path,
    tons_per_person: float,
    lat: float,
    lon: float,
    radius: int,
    stride: float,
    nthreads: int,
    zoom: float,
) -> str:
    """Build the justPop.exe command string."""
    return (
        f"{exe_path} -f {output} "
        f"-t {tons_per_person} "
        f"--lat={lat} --lon={lon} "
        f"--radius={radius} "
        f"--stride={stride} "
        f"--nthreads={nthreads} "
        f"--zoom={zoom}"
    )


def save_script(output_path: Path, cmd: str, rb_src: Path) -> Path:
    """Save the command to a shell script."""
    script_path = output_path.with_suffix(".sh")
    script_content = f"""#!/usr/bin/env bash

# This script is generated by 'rb-road-network'

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

{cmd}
"""
    script_path.write_text(script_content)
    script_path.chmod(0o755)
    return script_path


def _render_map(output_path: Path, rb_src: Path) -> None:
    """Invoke render_plotly.py to produce a PNG map from the JSON result."""
    json_path = output_path.with_suffix(".json")
    png_path = output_path.with_suffix(".png")
    render_script = rb_src / "render_scripts" / "render_plotly.py"
    if not render_script.exists():
        click.echo(f"(skipping render: render script not found at {render_script})")
        return
    if not json_path.exists():
        click.echo(f"(skipping render: JSON output not found at {json_path})")
        return
    click.echo(f"Rendering map to {png_path} ...")
    env = os.environ.copy()
    env["LD_LIBRARY_PATH"] = env.get("LD_LIBRARY_PATH", "") + ":/usr/local/lib"
    try:
        subprocess.run(
            [sys.executable, str(render_script), str(json_path), "--output", str(png_path)],
            cwd=str(rb_src),
            env=env,
            check=True,
        )
        click.echo(f"Map saved to: {png_path}")
    except subprocess.CalledProcessError as e:
        click.secho(
            f"Warning: map rendering failed (exit code {e.returncode}).",
            fg="yellow",
            err=True,
        )


@click.group()
def cli():
    """Rocky Branches Road Network CLI."""
    pass


@cli.command()
@click.option(
    "-f",
    "--output",
    type=click.Path(path_type=Path),
    default=None,
    help=f"Output file path (default: {DEFAULT_OUTPUT})",
)
@click.option(
    "-t",
    "--tons-per-person",
    type=float,
    default=None,
    help=f"Tons per person (default: {DEFAULT_TONS_PER_PERSON})",
)
@click.option(
    "--lat",
    type=float,
    default=None,
    help=f"Latitude in decimal degrees (default: {DEFAULT_LAT})",
)
@click.option(
    "--lon",
    type=float,
    default=None,
    help=f"Longitude in decimal degrees (default: {DEFAULT_LON})",
)
@click.option(
    "-r",
    "--radius",
    type=int,
    default=None,
    help=f"Radius in meters (default: {DEFAULT_RADIUS})",
)
@click.option(
    "-s",
    "--stride",
    type=float,
    default=None,
    help=f"Stride length (default: {DEFAULT_STRIDE})",
)
@click.option(
    "-h",
    "--nthreads",
    type=int,
    default=None,
    help=f"CPU threads (default: auto-detect)",
)
@click.option(
    "-z",
    "--zoom",
    type=float,
    default=None,
    help=f"Zoom ratio (default: {DEFAULT_ZOOM})",
)
@click.option(
    "--no-exec",
    is_flag=True,
    help="Save script but don't execute",
)
@click.option(
    "-y",
    "--yes",
    is_flag=True,
    help="Skip confirmation prompts (non-interactive mode)",
)
@click.option(
    "--rb-src",
    type=click.Path(exists=True, path_type=Path),
    default=None,
    help="Path to RB_SRC directory (default: $RB_SRC or current directory)",
)
@click.option(
    "--render/--no-render",
    default=True,
    help="Render a map PNG after computation (default: render)",
)
def run(
    output,
    tons_per_person,
    lat,
    lon,
    radius,
    stride,
    nthreads,
    zoom,
    no_exec,
    yes,
    rb_src,
    render,
):
    """Run the population analysis."""
    if rb_src is None:
        rb_src = get_rb_src()

    interactive = (
        output is None
        or tons_per_person is None
        or lat is None
        or lon is None
        or radius is None
        or stride is None
        or zoom is None
    )

    if interactive and not yes:
        click.echo("Hi, welcome to the Rocky Branches Road Network Interface!\n")

    if output is None:
        default_output = rb_src / DEFAULT_OUTPUT
        output = click.prompt(
            "Output path",
            default=str(default_output),
            type=str,
        )
        output = Path(output)

    if tons_per_person is None:
        tons_per_person = click.prompt(
            "Tons per person",
            default=str(DEFAULT_TONS_PER_PERSON),
            type=float,
        )

    if lat is None:
        lat = click.prompt(
            "Latitude in decimal degrees",
            default=str(DEFAULT_LAT),
            type=float,
        )

    if lon is None:
        lon = click.prompt(
            "Longitude in decimal degrees",
            default=str(DEFAULT_LON),
            type=float,
        )

    if radius is None:
        radius = click.prompt(
            "Radius in meters",
            default=str(DEFAULT_RADIUS),
            type=int,
        )

    if stride is None:
        stride = click.prompt(
            "Stride length",
            default=str(DEFAULT_STRIDE),
            type=float,
        )

    if nthreads is None:
        default_threads = os.cpu_count() or 4
        nthreads = click.prompt(
            "CPU threads",
            default=str(default_threads),
            type=int,
        )

    if zoom is None:
        zoom = click.prompt(
            "Zoom ratio",
            default=str(DEFAULT_ZOOM),
            type=float,
        )

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)

    exe_path = get_justpop_exe(rb_src)

    cmd = build_command(
        exe_path,
        output,
        tons_per_person,
        lat,
        lon,
        radius,
        stride,
        nthreads,
        zoom,
    )

    click.echo("\nThanks! Now computing with indicated settings...\n")

    settings = f"""[Settings]:
output path: {output}
lat = {lat}, lon = {lon}
radius = {radius} meters
tons_per_person = {tons_per_person}
stride = {stride}
zoom = {zoom}
nthreads = {nthreads}
"""
    click.echo(settings)

    click.echo(f"Full command:\n'{cmd}'\n")

    script_path = save_script(output, cmd, rb_src)
    click.echo(f"Saved the full command to: '{script_path}'\n")

    if no_exec:
        click.echo("Skipping execution (--no-exec flag set)")
        return

    if not yes:
        contflag = click.prompt("Continue?", default="y", type=str)
        if contflag.lower() != "y":
            click.echo("Ok. Exiting then... :)")
            return

    click.echo("Launching...")

    env = os.environ.copy()
    env["LD_LIBRARY_PATH"] = env.get("LD_LIBRARY_PATH", "") + ":/usr/local/lib"

    try:
        subprocess.run(
            cmd,
            shell=True,
            cwd=str(rb_src),
            env=env,
            check=True,
        )
        click.echo("...done.")
    except subprocess.CalledProcessError as e:
        click.secho(
            f"Error: Command failed with exit code {e.returncode}", fg="red", err=True
        )
        sys.exit(e.returncode)

    if render:
        _render_map(output, rb_src)


@cli.command()
@click.option(
    "--csv",
    "csv_file",
    type=click.Path(exists=True, path_type=Path),
    required=True,
    help="Path to CSV file with columns: site, lat, lon",
)
@click.option(
    "-t",
    "--tons-per-person",
    type=float,
    default=DEFAULT_TONS_PER_PERSON,
    show_default=True,
    help="Tons per person",
)
@click.option(
    "-r",
    "--radius",
    type=int,
    default=DEFAULT_RADIUS,
    show_default=True,
    help="Radius in meters",
)
@click.option(
    "-s",
    "--stride",
    type=float,
    default=DEFAULT_STRIDE,
    show_default=True,
    help="Stride length",
)
@click.option(
    "-h",
    "--nthreads",
    type=int,
    default=None,
    help="CPU threads (default: auto-detect)",
)
@click.option(
    "-z",
    "--zoom",
    type=float,
    default=DEFAULT_ZOOM,
    show_default=True,
    help="Zoom ratio",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path),
    default=None,
    help="Directory for output files (default: <rb_src>/output/)",
)
@click.option(
    "--rb-src",
    type=click.Path(exists=True, path_type=Path),
    default=None,
    help="Path to RB_SRC directory (default: $RB_SRC or current directory)",
)
@click.option(
    "--render/--no-render",
    default=True,
    help="Render a map PNG for each result (default: render)",
)
@click.option(
    "--no-exec",
    is_flag=True,
    help="Save scripts but don't execute",
)
def batch(csv_file, tons_per_person, radius, stride, nthreads, zoom, output_dir, rb_src, render, no_exec):
    """Run population analysis for multiple sites from a CSV file.

    The CSV must contain columns: site, lat, lon
    """
    if rb_src is None:
        rb_src = get_rb_src()

    if output_dir is None:
        output_dir = rb_src / "output"
    output_dir.mkdir(parents=True, exist_ok=True)

    if nthreads is None:
        nthreads = os.cpu_count() or 4

    exe_path = get_justpop_exe(rb_src)

    required_cols = {"site", "lat", "lon"}
    rows = []
    with open(csv_file, newline="") as f:
        reader = csv.DictReader(f)
        headers = {h.lower() for h in (reader.fieldnames or [])}
        if not required_cols.issubset(headers):
            missing = required_cols - headers
            raise click.ClickException(
                f"CSV is missing required columns: {', '.join(sorted(missing))}"
            )
        for row in reader:
            rows.append({k.lower(): v for k, v in row.items()})

    if not rows:
        click.echo("No rows found in CSV. Nothing to do.")
        return

    click.echo(f"Starting batch run for {len(rows)} site(s) from {csv_file}\n")

    env = os.environ.copy()
    env["LD_LIBRARY_PATH"] = env.get("LD_LIBRARY_PATH", "") + ":/usr/local/lib"

    for row in rows:
        site = "".join(c for c in row["site"] if c not in ' /\'":\t')
        lat = float(row["lat"])
        lon = float(row["lon"])
        output = output_dir / f"{site}Result.txt"

        cmd = build_command(exe_path, output, tons_per_person, lat, lon, radius, stride, nthreads, zoom)
        script_path = save_script(output, cmd, rb_src)

        click.echo(f"[{site}] lat={lat}, lon={lon}")
        click.echo(f"  output: {output}")
        click.echo(f"  script: {script_path}")

        if no_exec:
            click.echo("  (skipping execution: --no-exec)")
            continue

        click.echo("  Launching...")
        try:
            subprocess.run(
                cmd,
                shell=True,
                cwd=str(rb_src),
                env=env,
                check=True,
            )
            click.echo("  ...done.")
        except subprocess.CalledProcessError as e:
            click.secho(
                f"  Error: [{site}] failed with exit code {e.returncode}",
                fg="red",
                err=True,
            )
            continue

        if render:
            _render_map(output, rb_src)

    click.echo("\nBatch run complete.")


if __name__ == "__main__":
    cli()
