# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."rb-roads" = {
    image = "localhost/compose2nix/rb-roads";
    environment = {
      "LD_LIBRARY_PATH" = "/usr/local/lib:/usr/local/lib:";
      "RBPATH" = "/home/appuser/rb_app";
      "RB_DATA" = "/home/appuser/rb_data";
      "RB_SRC" = "/home/appuser/rb_app";
      "USER" = "appuser";
      "XDG_DATA_DIRS" = "/home/robbiec/Git/rb-road-network/share:/home/robbiec/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:/home/robbiec/.nix-profile/share:/nix/var/nix/profiles/default/share:/usr/share";
    };
    environmentFiles = [
      "/home/robbiec/Git/rb-road-network/.envrc"
      "/home/robbiec/Git/rb-road-network/docker/docker.envrc"
    ];
    volumes = [
      "/home/robbiec/Documents/rb_data:/home/appuser/rb_data:rw"
    ];
    ports = [
      "8888:8888/tcp"
    ];
    cmd = [ "/bin/bash" "-c" "echo 'Container is running....' && read -p 'Press any key to open a shell...' && echo 'Key pressed. Opening shell...' && /bin/bash /home/appuser/rb_app/scripts/roads_rb" ];
    user = "appuser";
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"/bin/bash\", \"-c\", \"echo 'Container is running....' && read -p 'Press any key to open a shell...' && echo 'Key pressed. Opening shell...' && /bin/bash /home/appuser/rb_app/scripts/roads_rb\"]"
      "--network-alias=rb-roads"
      "--network=rb-road-network_rb-roads-network"
    ];
  };
  systemd.services."podman-rb-roads" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-rb-road-network_rb-roads-network.service"
    ];
    requires = [
      "podman-network-rb-road-network_rb-roads-network.service"
    ];
    partOf = [
      "podman-compose-rb-road-network-root.target"
    ];
    wantedBy = [
      "podman-compose-rb-road-network-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-rb-road-network_rb-roads-network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f rb-road-network_rb-roads-network";
    };
    script = ''
      podman network inspect rb-road-network_rb-roads-network || podman network create rb-road-network_rb-roads-network --driver=bridge
    '';
    partOf = [ "podman-compose-rb-road-network-root.target" ];
    wantedBy = [ "podman-compose-rb-road-network-root.target" ];
  };

  # Builds
  systemd.services."podman-build-rb-roads" = {
    path = [ pkgs.podman pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/robbiec/Git/rb-road-network
      podman build -t compose2nix/rb-roads -f ./docker/Dockerfile .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-rb-road-network-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
