#!/usr/bin/env bash

# This script is generated by scripts/roads_rb

export LD_LIBRARY_PATH=:/usr/local/lib

/home/robbiec/Git/rb-road-network/justPop.exe -f /home/robbiec/Documents/rb_data/output/bluejayresult.txt -t 4.50 --lat=35.4709556 --lon=-81.5175694 --radius=75000 --stride=0.009 --nthreads=16 --zoom=0.5

