#!/usr/bin/env bash

# This script is generated by scripts/roads_rb

export LD_LIBRARY_PATH=:/usr/local/lib

/home/robbiec/Git/rb-road-network/justPop.exe -f /home/robbiec/Git/rb-road-network/output/DiggsSouthSandResult.txt -t 4.50 --lat=36.0260084 --lon=-89.6864944 --radius=75000 --stride=0.009 --nthreads=2 --zoom=0.5

