#!/usr/bin/env bash

# This script is generated by scripts/roads_rb

export LD_LIBRARY_PATH=:/usr/local/lib

/home/robbiec/Git/rb-road-network/justPop.exe \
    -f /home/robbiec/Git/rb-road-network/output/DiggsSouthSandResultFixed.txt \
    -t 3.03 \
    --lat=36.02899899 \
    --lon=-90.313214999 \
    --radius=75000 \
    --stride=0.009 \
    --nthreads=4 \
    --zoom=0.5

