#!/usr/bin/env sh

set -e

# This script is generated by '/home/robbiec/Git/rb-road-network/scripts/roads_rb'

export LD_LIBRARY_PATH=:/usr/local/lib

/home/robbiec/Git/rb-road-network/justPop.exe \
    -f /home/robbiec/Git/rb-road-network/output/PigeonPointResult.txt \
    -t 4.50 --lat=32.8131 --lon=-84.5489 --radius=75000 --stride=0.009 --nthreads=2 --zoom=0.5
