#!/usr/bin/env bash

# This script is generated by scripts/roads_rb

export LD_LIBRARY_PATH=/home/robbiec/.local/lib:/home/robbiec/.local/lib/x86_64-linux-gnu:/home/robbiec/.local/lib:/home/robbiec/.local/lib/x86_64-linux-gnu::/usr/local/lib

/home/robbiec/Git/rb-road-network/justPop.exe -f /home/robbiec/Git/rb-road-network/output/RobinRidgeResult.txt -t 4.50 --lat=35.6314 --lon=-80.2270 --radius=75000 --stride=0.009 --nthreads=16 --zoom=0.5

