#!/usr/bin/env bash
# This script is generated by scripts/roads_rb

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

$HOME/Git/rb-road-network/justPop.exe -f $HOME/Git/rb-road-network/output/SavannaLatestResult5.txt -t 3.03 --lat=32.066051 --lon=-81.095341 --radius=75000 --stride=0.006 --nthreads=16 --zoom=0.525
