#!/bin/bash
# extract bounding box, refer to this page: https://osmcode.org/osmium-tool/manual.html#creating-geographic-extracts
# args: [bbox] [output_fn]
osmium extract -b $1 $RB_DATA/gis_osm_roads/us-latest.pbf -o $2
